/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-FAHlbYvy-BB1wo4gACuIU0YM9tIPS--0B8uSXWT0B5zyxHxQEqXFyy70hn5ec53qWhDGynnV46LsXjFyq2gByfcUwuR6e6I1PQJmEJMnqFCmkt2jllBnRvRA",
  "tt": "tt-1-TjO-avMKkkNEqX37HwQownvWB3w0M-c9cRDOvhHhkSU=",
  "version": "2020-11-20"
}

export default ebconfig;